name: Justpets.ca
favicon: null
layout_spectrum: 0.40948012098670006
typography_spectrum: 0.96931
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#18251b'
    - '#fdfdfb'
    - '#6d636b'
    - '#7990a0'
    - '#b0c5d6'
  brandStrength: 0.625
  lightness: 0.07956161559559405
  saturation: 0.6072380635887384
  rhythmicContrast: 0.2617908758111298
purpose: []
